### ISSUE TITLE
Using `zip -s- <infiles> --out <outfile>` truncates file to 4 GB

### ISSUE THREAD

**Issue by altsan** [bitwiseworks/rpm-issues#1]
**Describe the bug**
The documented way to restore a multi-volume ZIP archive (created with zip -s) is to reconstruct it as a single file using `zip -s- _input_file_ --out _output_file_`.  However, doing so causes _output_file_ to  be truncated at 4GB, rendering it unusable.

**To Reproduce**
Given these files:
        17,179,869 K      reinforce_e_20170630.z01
        15,842,605 K      reinforce_e_20170630.zip
Use this command to recombine them:
        zip -s- reinforce_e_20170630 --out g:\restore\combined_e_20170630.zip

This appears to work.  However, the resultant output file is 
        4,294,967 K    combined_e_20170630.zip
instead of the expected 33 GB, and is not recognized as a valid ZIP file

**Expected behavior**

The combined output file should be ~33 GB and recognized as a valid ZIP by unzip.exe.

**Desktop (please complete the following information):**
OS is ArcaOS 5

Info-Zip is Zip 3.0 (July 5th 2008).
Compiled with emx+gcc 4.9.2 for OS/2 2.x/3.x (32-bit) on Sep 28 2018.
Installed from RPM:  zip.i686  3.0-8.oc00

**Additional context**

The target filesystem is JFS. The source files are located on a NAS drive.

This may be related: http://trac.netlabs.org/ports/ticket/201

**Comment by SilvanScherrer** [comment]
Please use the debug function -lf -li to get more insight. And copy the logfile in here

**Comment by altsan** [comment]
OK.  I assume you don't want the _full_ logfile, which is 35 MB.  However, other than the start and end it's just a list of the files being copied, so I'll quote just that here.  Let me know if you really do want the whole thing (2.5 MB 7z'd).

---------
Zip log opened Tue Dec 31 20:06:38 2019
command line arguments:
 -s- -li -lf debug.log --out e:\tmp\test.zip reinforce_g_20191116

 copying: $SYSINDX.FNT
 copying: acct.ini
 copying: addbl.cmd
 copying: adjust.log
 copying: altboot_config.sys

-- snip --

 copying: _no/helv/Font1032.fnt
 copying: _no/helv/Font1033.fnt
 copying: _no/helv/helv.rc
 copying: _no/helv/helv.RES
 copying: _no/helv/original/
 copying: _no/helv/original/HELV.FON
total bytes=25138227444, compressed=19702353344 -> 22% savings

Total 479439 entries (18G bytes)
Done Tue Dec 31 21:06:23 2019

And the actual output file is:
[E:\tmp]ls -l test.zip
-rw-r--r-- 1 root root 4294967295 Dec 31 21:06 test.zip

**Comment by SilvanScherrer** [comment]
I will look at it later. But a next question. What FS is your E drive? And does the file size ever grow below 4gb during copy?

**Comment by altsan** [comment]
Drive E: is JFS (latest Arca Noae version).  I haven't monitored the file size during the copy process.  (IIRC it writes to a temporary file during execution and then renames it, I guess that's the file you mean.)

**Comment by SilvanScherrer** [comment]
Yes it writes to a temp file. Iirc at the same location as the end result. Please try to see if it grows over 4gb  at all or if it stays at 4gb then as well.

**Comment by altsan** [comment]
OK. Since each test takes several hours to run, I'll try and do that this weekend.

**Comment by altsan** [comment]
OK, I can confirm that the temporary file does grow well past 4 GB (I see 9.4 GB and growing at current count).  

(FWIW, the temp file is created on the source drive, not the target drive.)

**Comment by SilvanScherrer** [comment]
Ok thx i will look at it. I might give you a more verbose Version to try.

**Comment by SilvanScherrer** [comment]
there is a zip.exe at http://rpm.netlabs.org/test/ it has some more vebose messages. so please use it with the -v switch. -lf -li is not needed for that. As I wonder which code path is uses. I guess it's not necessary to have such a big zip file. As I suspect everything bigger than 4gb fails. After those messages I know if it does a real copy or if it does a rename()

**Comment by SilvanScherrer** [comment]
there is also a zip_01.exe please try it as well. As it might fix the issue.

**Comment by altsan** [comment]
OK, thanks.  I have tested both builds.

Testing with the first zip.exe, log attached.

**Comment by altsan** [comment]
Testing with zip_01.exe.  This works, the file is now the correct output size!
Log attached.
[test_combined2.log](https://github.com/bitwiseworks/rpm-issues/files/4038418/test_combined2.log)

**Comment by SilvanScherrer** [comment]
Ok great new rpm fix the fix comes today

**Comment by SilvanScherrer** [comment]
new rpm uploaded to exp repo.
fixed with https://github.com/bitwiseworks/zip-os2/commit/15c2296c6f0ab655cb501184be7369d861cb109f
