### ISSUE TITLE
klusrmgr: Superfluous POSTIN scriptlet failure warning

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/rpm-issues#11]
Updating to the latest version gives this:
```
Non-fatal POSTIN scriptlet failure in rpm package klusrmgr-1.4.1-1.oc00.i686
Group "wheel" is invalid - cannot remove!
warning: %post(klusrmgr-1.4.1-1.oc00.i686) scriptlet failed, exit status 252
```
It makes no sense to show this warning to the user as it's not something that indicates a problem -- it will just confuse them.

Maybe it's klusrmgr tool that should be fixed but in either case the warning should be suppressed in POSTIN scriptlet.

**Comment by SilvanScherrer** [comment]
Should be fixed in the last rpm. Please test.

**Comment by SilvanScherrer** [comment]
no comment, so we assume all is fine
