### ISSUE TITLE
SANE packaging: add "sane-backends-drivers-scanners" as requirement to "sane-backends"

### ISSUE THREAD

**Issue by lerdmann** [bitwiseworks/rpm-issues#12]
The SANE SW (scanimage.exe in particular) is useless from a user's perspective if the various scanner specific DLLs are not installed along with it.
I therefore suggest to add these as a requirement/prerequisite.

**Comment by SilvanScherrer** [comment]
The Installation of sane-backends-scaner requires sane-backends and sane-backends-libs. The reason is that there are backends which are just using the same part. But are not in the sane-backends-scaner list. So its a hard decision if we should add it. I will think about it.

**Comment by SilvanScherrer** [comment]
this is also the way fedora does it. So we guess it's right. if fedora changes it, it will be aligned as well when we resync.
