### ISSUE TITLE
SANE packaging: remove "usbcalls" as requirement from "sane-backends"

### ISSUE THREAD

**Issue by lerdmann** [bitwiseworks/rpm-issues#13]
The USBCALLS.DLL that is contained in the "usbcalls" package (with PIPPO listed as creator)  is outdated and also not fully binary compatible with the USBCALLS.DLL that is delivered by AN or by my USB driver set (some routines are missing while deprecated routines are still implemented -  even for the routines that are common to both,  I don't know if the internal implementation is sufficiently equivalent). Note that a few years ago, there had been heavy rework and cleanup of USBCALLS.DLL.

In addition, the AN stack will always test for compatiblity between USBCALLS.DLL and USBRESMG.SYS and will therefore fail with this outdated version of USBCALLS.DLL.

Wim Brul has also proven that current version of USBCALLS.DLL properly interacts with the SANE RPM (or more specifically: usb100.dll).

1) suggest to remove that package as requirement to "sane-backends"
2) suggest to completely remove package "usbcalls" and "usbcalls-debug" from the RPM repo

**Comment by SilvanScherrer** [comment]
This req is generated automatically, as the dll is needed. So this cant be worked around. To remove the old usbcalls rpm is no Problem. We will do it. This at least gives the right usbcalls for AN customers. As the have AN repos available. And if your usbcalls are binary compatible with AN we could create a new rpm. So non AN customers still can use it.
Just advise if you like the idea

**Comment by lerdmann** [comment]
I can confirm that the interface of USBCALLS.DLL of AN and my implementation is identical.
As long as no additional USBCALLS.DLL is installed (but instead, the one located in \OS2\DLL is used which is true for AN as well as for my USB driver package and this DLL is part of every AN USB driver installation) I agree to any possible solution.

**Comment by SilvanScherrer** [comment]
done in latest usbcalls rpm
