### ISSUE TITLE
Bug tracker needs updating

### ISSUE THREAD

**Issue by dryeo** [bitwiseworks/rpm-issues#19]
**Describe the bug**
Currently a failure in ANPM suggests reporting the issue to http://trac.netlabs.org/rpm/
This is caused by the setting in @unixroot\etc\yum\yum.conf, not sure how it can be updated but something like,
```
--- yum.conf.orig       2021-10-10 14:51:16.000000000 -0700
+++ yum.conf    2021-10-10 14:51:56.000000000 -0700
@@ -5,7 +5,7 @@
 logfile=/var/log/yum.log
 exactarch=1
 obsoletes=1
-bugtracker_url=http://trac.netlabs.org/rpm/
+bugtracker_url=https://github.com/bitwiseworks/rpm-issues/
```
Gives a better result

**Comment by SilvanScherrer** [comment]
should be fixed in latest yum rpm.
