### ISSUE TITLE
Error trying to update git to 2.30.2

### ISSUE THREAD

**Issue by lerdmann** [bitwiseworks/rpm-issues#20]
I get this when I try to update to git 2.30.2:

ERROR with transaction check vs depsolve:
perl(Authen::SASL) wird benötigt von git-email-2.30.2-1.oc00.noarch
perl(Net::SMTP::SSL) wird benötigt von git-email-2.30.2-1.oc00.noarch
Bitte melden Sie diesen Fehler unter https://github.com/bitwiseworks/rpm-issues

I do not have git-email installed and attempting to do so will also fail.

**Comment by SilvanScherrer** [comment]
I need to check that. Thx for reporting.

**Comment by SilvanScherrer** [comment]
please give me the output of yum list git*. As git core doesn't trigger email at all. Could it be you have git-all installed?

**Comment by lerdmann** [comment]
1) yes, I do have "git-all" installed
2) here is the dump of "yum list git*":
`Installierte Pakete
git.pentium4                          2.11.0-4.oc00                 installed   
git-all.noarch                        2.11.0-4.oc00                 @netlabs-rel
git-core.pentium4                     2.11.0-4.oc00                 installed   
git-core-doc.pentium4                 2.11.0-4.oc00                 installed   
git-p4.noarch                         2.11.0-4.oc00                 installed   
Verfgbare Pakete
git.i386                              2.0.0-2.oc00                  netlabs-rel 
git.i686                              2.11.0-4.oc00                 netlabs-rel 
git.pentium4                          2.30.2-2.oc00                 netlabs-exp 
git-all.noarch                        2.30.2-2.oc00                 netlabs-exp 
git-bzr.noarch                        2.0.0-2.oc00                  netlabs-rel 
git-core.i686                         2.11.0-4.oc00                 netlabs-rel 
git-core.pentium4                     2.30.2-2.oc00                 netlabs-exp 
git-core-doc.i686                     2.11.0-4.oc00                 netlabs-rel 
git-core-doc.noarch                   2.30.2-2.oc00                 netlabs-exp 
git-cvs.noarch                        2.11.0-3.oc00                 netlabs-rel 
git-daemon.i386                       2.0.0-2.oc00                  netlabs-rel 
git-daemon.i686                       2.11.0-4.oc00                 netlabs-rel 
git-daemon.pentium4                   2.30.2-2.oc00                 netlabs-exp 
git-debug.i386                        2.0.0-2.oc00                  netlabs-rel 
git-debug.i686                        2.0.0-2.oc00                  netlabs-rel 
git-debug.pentium4                    2.0.0-2.oc00                  netlabs-rel 
git-debuginfo.i686                    2.11.0-4.oc00                 netlabs-rel 
git-debuginfo.pentium4                2.30.2-2.oc00                 netlabs-exp 
git-email.noarch                      2.30.2-1.oc00                 netlabs-exp 
git-hg.noarch                         2.0.0-2.oc00                  netlabs-rel 
git-p4.noarch                         2.30.2-2.oc00                 netlabs-exp 
git-subtree.pentium4                  2.30.2-2.oc00                 netlabs-exp 
git-svn.i386                          2.0.0-2.oc00                  netlabs-rel 
git-svn.i686                          2.11.0-3.oc00                 netlabs-rel 
git-svn.pentium4                      2.11.0-3.oc00                 netlabs-rel 
gitweb.i386                           1.7.6.1-7.oc00                netlabs-rel 
`

**Comment by lerdmann** [comment]
uninstalled "git-all", then updated "git" which pulled in a couple of other RPMs. The update to git 2.30.2 then worked without any problems.
