### ISSUE TITLE
QT5-linguist package doesn't setup it sym-links and/or environment correctly.

### ISSUE THREAD

**Issue by Greggk** [bitwiseworks/rpm-issues#21]
After installing QT5-linguist I tried running lupdate-qt5.exe with a .pro file on the command line I get the following sh.exe: 1: J:/usr/bin/lprodump.exe: not found
sh.exe: 1: J:/usr/bin/lupdate.exe: not found

If I run it without anything on the command line I get the Usage as expected so any needed dlls are installed.

If I rename lupdate-qt5 to lupdate and run it with a .pro file I get WARNING: Cannot find feature spec_pre.prf (this file is present in the features directory)
lupdate error: illegal value in U:/Kalendar_Workspace/kalendar/kalendar/src/gJYqlW.json at offset 0. (this file doesn't exist)

This is using 4os2 as the shell

We tried installing on a different system and got the same results

If I use the lupdate from QT4 with the same .pro file it generates the .ts files as expected.

**Comment by dmik** [comment]
This is a duplicate. Already reported and will be fixed by a next RPM build, see also https://github.com/bitwiseworks/qttools-os2/issues/2 (and https://github.com/bitwiseworks/rpm-specs/commit/0edb0fe365ea29970ad01384dcd473c3635b4d31 although it's for the record as not publicly available).
