### ISSUE TITLE
SIP update fails

### ISSUE THREAD

**Issue by abwillis** [bitwiseworks/rpm-issues#23]
Attempting to update SIP it has a dependency of python2-sip-devel, which then gives:
ERROR with transaction check vs depsolve:sip-api(11) >= 11.3 is needed by (installed) PyQt4-4.11.4-3.oc00.pentium4
Please report this error at https://github.com/bitwiseworks/rpm-issues

**Comment by SilvanScherrer** [comment]
a new pyqt4 is needed to get that working. it will happen soon I hope

**Comment by SilvanScherrer** [comment]
should work. if not please reopen the ticket with a new log plesase.
