### ISSUE TITLE
ANPM / Yum error when trying to update QT5 

### ISSUE THREAD

**Issue by scrutch2001** [bitwiseworks/rpm-issues#26]
Error message from ANPM when trying to update QT5:

ERROR with transaction check vs depsolve:qt5-qtbase = 5.15.2-1.oc00 is needed by qt5-qtbase-common-5.15.2-1.oc00.noarchqt5-qtbase-common = 5.13.1-1.oc00 is needed by (installed) qt5-qtbase-5.13.1-1.oc00.i686qt5-qttools-common = 5.13.1-1.oc00 is needed by (installed) qt5-qttools-5.13.1-1.oc00.i686Please report this error at https://github.com/bitwiseworks/rpm-issues

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arca Noae 5.0.7
 - Browser Firefox 45.9]

**Additional contex

**Comment by SilvanScherrer** [comment]
you need to enable pentium4 arch in anpm, as there is no new qt5 in i686 arch.
If this doesn't fix it, please reopen the issue again.
