### ISSUE TITLE
ANPM error update Poppler

### ISSUE THREAD

**Issue by RonKlein32** [bitwiseworks/rpm-issues#29]
When I try to update poppler with ANPM, I get the following error:
ERROR with transaction check vs depsolve:poppl101.dll is needed by poppler-cpp-0.90.1-1.oc00.pentium4poppler = 0.90.1-1.oc00 is needed by poppler-cpp-0.90.1-1.oc00.pentium4poppl101.dll is needed by poppler-utils-0.90.1-1.oc00.pentium4poppler = 0.90.1-1.oc00 is needed by poppler-utils-0.90.1-1.oc00.pentium4Please report this error at https://github.com/bitwiseworks/rpm-issues
current version is: 0.84.0-1 (oc00)  i686
attempting to update to: 0.90.1-1oc00 available on 'netlabs-rel'

**To Reproduce**
1. Open ANPM
2. Select poppler
3. Click on "Selected' -> Update
5. See  above error

**Expected behavior**
poppler updated

**Desktop (please complete the following information):**
 - OS: ArcaOS 5.0.8
 - Browser Firefox
 - Version 45.9.0

ANPM version 1.1.0.2

**Comment by SilvanScherrer** [comment]
attach the complete log, but not from ANPM. use cmd line only

**Comment by RonKlein32** [comment]
I am not familiar with using the command line to update an RPM package, which is why I use ANPM.  I would appreciate some guidance  to formulate the command to do the update.  I presume I would need to point to the correct repository, also, before issuing the command.  Where would I find the log file after issuing the command?  Thanks.  Ron

**Comment by SilvanScherrer** [comment]
yum list poppler* > list.txt
yum update poppler 2>&1 | tee update.txt

**Comment by RonKlein32** [comment]
Attached are list.txt and update.txt
[update.txt](https://github.com/bitwiseworks/rpm-issues/files/12592922/update.txt)
[list.txt](https://github.com/bitwiseworks/rpm-issues/files/12592923/list.txt)

**Comment by SilvanScherrer** [comment]
you need to update all 3 poppler packages in one go. not only poppler itself.

**Comment by RonKlein32** [comment]
ANPM does try to update all 3 packages at once..  
ran yum update poppler poppler-cpp poppler-utils  2>&1 | tee update1.txt
attached is update1.txt
[update1.txt](https://github.com/bitwiseworks/rpm-issues/files/12613392/update1.txt)

**Comment by SilvanScherrer** [comment]
there seems to be something wrong on your system, as you have unfinished transactions. If this is the root case I dont know. 
To what arch is ANPM set? Pentium4?

**Comment by RonKlein32** [comment]
ANPM has a file called platforms.lst:
;This file lists all platforms which may be available on the repo(s).
;Order is not significant.
i386
i686
pentium4

At this time, it is a moot point.  I am going to install ArcaOS 5.1.0 from scratch.  You may close this problem.  If I still have problems after installing the new system, I will open another problem.
Thank you for your help.
Ron Klein
