### ISSUE TITLE
Please create debuginfo package for kbuild-make

### ISSUE THREAD

**Issue by StevenLevine** [bitwiseworks/rpm-issues#3]
Please create debuginfo package for kbuild-make.

**Comment by dmik** [comment]
Yes, it's missing indeed, thanks for noticing. The next RPM will have it.

**Comment by StevenLevine** [comment]
Any idea when this might be?  Alex and I are working on a issue where make hangs in the exit list.  I can see the code path that's causing the hang, but need to collect better data before submitting an issue to, I assume, the kbuild-os2 project.

**Comment by dmik** [comment]
Closing this in favor of #4 as it's a per .spec procedure. There is a single debuginfo sub-plackage for all packages generated from .spec.
