### ISSUE TITLE
AcaOS 5.0 Package Manager error

### ISSUE THREAD

**Issue by makedigital5** [bitwiseworks/rpm-issues#31]
When trying to update allin the Arca Noae Package Manager, I receive this error.

ERROR with transaction check vs depsolve:python(abi) = 2.7 is needed by (installed) yum-utils-1.1.31-3.oc00.noarchpython(abi) = 2.7 is needed by (installed) python2-rpm-4.13.0-20.oc00.pentium4python(abi) = 2.7 is needed by (installed) urlgrabber-3.10.1-10.oc00.noarchpython(abi) = 2.7 is needed by (installed) yum-3.4.3-14.oc00.pentium4python(abi) = 2.7 is needed by (installed) yum-metadata-parser-1.1.4-7.oc00.pentium4/@unixroot/usr/bin/python2 is needed by (installed) hplip-3.19.8-3.oc00.pentium4python27.dll is needed by (installed) hplip-libs-3.19.8-3.oc00.pentium4python27.dll is needed by (installed) python2-rpm-4.13.0-20.oc00.pentium4python27.dll is needed by (installed) yum-metadata-parser-1.1.4-7.oc00.pentium4python(abi) = 2.7 is needed by python2-pycurl-7.44.1-3.oc00.pentium4python27.dll is needed by python2-pycurl-7.44.1-3.oc00.pentium4Please report this error at https://github.com/bitwiseworks/rpm-issues

When I run "yum update" from the Command Prompt, there seems to be an indication of a dependency problem due to obsolete packages.

**Comment by SilvanScherrer** [comment]
First do yum install python3 python2.7,then all should be fine

**Comment by tomtom-66** [comment]
> First do yum install python3 python2.7,then all should be fine

It appears that this solution should be changed into: 

yum install  python2.7 python3 python-unversioned-command
