### ISSUE TITLE
How to deal with ANPM conflicts?

### ISSUE THREAD

**Issue by aypeyret** [bitwiseworks/rpm-issues#32]
While applying updates to ArcaOS 5.1.0, I often get errors of the following type. In the example below, the updates were cmake (3.15.3 to 3.20.6, more than one package), flac-libs (1.3.3-1 to 1.3.4-1), qt5 (5.13.1-1 to 5.15.2-1). The updates of qt5 and flac-libs by themselves succeeded, so the culprit is in cmake. I do not mind reporting that but where exactly (here?)? What other kind of info may be needed? How to solve these conflicts?

******
ERROR with transaction check vs depsolve:python(abi) = 2.7 is needed by python2-pycurl-7.44.1-3.oc00.pentium4python27.dll is needed by python2-pycurl-7.44.1-3.oc00.pentium4python27.dll is needed by (installed) yum-metadata-parser-1.1.4-7.oc00.pentium4python27.dll is needed by (installed) python2-rpm-4.13.0-20.oc00.pentium4python27.dll is needed by (installed) hplip-libs-3.19.8-3.oc00.pentium4python(abi) = 2.7 is needed by (installed) urlgrabber-3.10.1-10.oc00.noarchpython(abi) = 2.7 is needed by (installed) yum-metadata-parser-1.1.4-7.oc00.pentium4python(abi) = 2.7 is needed by (installed) yum-utils-1.1.31-3.oc00.noarchpython(abi) = 2.7 is needed by (installed) python2-rpm-4.13.0-20.oc00.pentium4python(abi) = 2.7 is needed by (installed) yum-3.4.3-14.oc00.pentium4/@unixroot/usr/bin/python2 is needed by (installed) hplip-3.19.8-3.oc00.pentium4

Please report this error at https://github.com/bitwiseworks/rpm-issues

**Comment by SilvanScherrer** [comment]
see https://github.com/bitwiseworks/rpm-issues/issues/31
if this doesn't help, reopen the ticket
