### ISSUE TITLE
ANPM stops loading rpm package list after crash

### ISSUE THREAD

**Issue by aypeyret** [bitwiseworks/rpm-issues#33]
ANPM crashed while attempting to update some packages. After trying to restart it, the list of installed rpms is not populated anymore and the following appears in the VX-REXX console:

A non-recoverable error occurred.  The process ended.
A non-recoverable error occurred.  The process ended.
1: DosConnectNPipe
A non-recoverable error occurred.  The process ended.

Is there some temp file to delete to recover from that problem ?

**Comment by aypeyret** [comment]
In the popuplog.os2:

03-14-2024  11:47:37  SYS2070  PID 0196  TID 0001  Slot 0097
C:\USR\BIN\PYTHON2.7.EXE
SSH21->LIBCN0.2026
182

**Comment by SilvanScherrer** [comment]
anpm is not our product. you need to send those kind of messages to arcanoae.
But it might be a restart of the system helps.

**Comment by SilvanScherrer** [comment]
No comment since long. Do we assume its fixed

**Comment by aypeyret** [comment]
I have not had much time to play with ArcaOS lately, so probably not fixed for me. I will get back to you when I do manage to find out.


On Dec 7, 2024, at 15:29, Silvan Scherrer ***@***.***> wrote:

﻿

No comment since long. Do we assume its fixed
