### ISSUE TITLE
Package Manager upgrade ERROR

### ISSUE THREAD

**Issue by tkoker** [bitwiseworks/rpm-issues#35]
ERROR with transaction check vs depsolve:python(abi) = 2.7 is needed by python2-pycurl-7.44.1-3.oc00.pentium4python27.dll is needed by python2-pycurl-7.44.1-3.oc00.pentium4python27.dll is needed by (installed) yum-metadata-parser-1.1.4-7.oc00.pentium4python27.dll is needed by (installed) python2-rpm-4.13.0-20.oc00.pentium4python27.dll is needed by (installed) hplip-libs-3.19.8-3.oc00.pentium4python(abi) = 2.7 is needed by (installed) urlgrabber-3.10.1-10.oc00.noarchpython(abi) = 2.7 is needed by (installed) yum-metadata-parser-1.1.4-7.oc00.pentium4python(abi) = 2.7 is needed by (installed) yum-utils-1.1.31-3.oc00.noarchpython(abi) = 2.7 is needed by (installed) python2-rpm-4.13.0-20.oc00.pentium4python(abi) = 2.7 is needed by (installed) yum-3.4.3-14.oc00.pentium4/@unixroot/usr/bin/python2 is needed by (installed) hplip-3.19.8-3.oc00.pentium4

**Comment by SilvanScherrer** [comment]
See #31 for the solution.
