### ISSUE TITLE
Error When Attempting to Update ArcaOSv2

### ISSUE THREAD

**Issue by jIyajbe** [bitwiseworks/rpm-issues#36]
**Describe the bug**
When I attempted to update ArcaOSv2 using the yum package manager, the update fails due to attempting to uninstall python2, which is needed by the yum package manager itself.

**To Reproduce**
1. Open Arca Noae Package Manager
2. Choose "Manage | Update All..."
3. Note that the updatable files includes [python-unversioned-command, python2-pycurl, python3, python3-libs, python3-pycurl]
4. Click "OK"
5. After downloads finish, the tool returns the following error:
"
ERROR with transaction check vs depsolve:', 'python(abi) = 2.7 is needed by python2-pycurl-7.44.1-3.oc00.pentium4', 'python27.dll is needed by python2-pycurl-7.44.1-3.oc00.pentium4', 'python27.dll is needed by (installed) python2-rpm-4.13.0-20.oc00.pentium4', 'python27.dll is needed by (installed) hplip-libs-3.19.8-3.oc00.i686', 'python27.dll is needed by (installed) yum-metadata-parser-1.1.4-7.oc00.i686', 'python(abi) = 2.7 is needed by (installed) yum-3.4.3-14.oc00.pentium4', 'python(abi) = 2.7 is needed by (installed) python2-rpm-4.13.0-20.oc00.pentium4', 'python(abi) = 2.7 is needed by (installed) yum-utils-1.1.31-3.oc00.noarch', 'python(abi) = 2.7 is needed by (installed) urlgrabber-3.10.1-10.oc00.noarch', 'python(abi) = 2.7 is needed by (installed) yum-metadata-parser-1.1.4-7.oc00.i686', '/@unixroot/usr/bin/python2 is needed by (installed) hplip-3.19.8-3.oc00.i686', u'
"

**Expected behavior**
All files should update

**Desktop (please complete the following information):**
 - OS: [ArcaOSv2]

**Additional context**

**Comment by SilvanScherrer** [comment]
See #35
