### ISSUE TITLE
Please create debuginfo package for kbuild

### ISSUE THREAD

**Issue by StevenLevine** [bitwiseworks/rpm-issues#4]
Please create debuginfo package for kbuild-os2.

**Comment by dmik** [comment]
I'm not quite sure what's referred to by `kbuild-os2`. We don't provide such a package...

**Comment by StevenLevine** [comment]
Sorry, kbuild-os is the github project name.  The package name is kbuild.

**Comment by dmik** [comment]
Okay, it will appear once the next RPM is released. I will leave it open till then. See also #3.

**Comment by SilvanScherrer** [comment]
with the latest kbuild debuginfo packages are around. If there are still issues feel free to reopen the ticket.
