### ISSUE TITLE
Crash in klusrmgr.exe during yum update

### ISSUE THREAD

**Issue by altsan** [bitwiseworks/rpm-issues#5]
**Describe the bug**
During an ArcaOS 5.0.5 beta update install, the installer runs 'yum update libc', which triggers several dependent updates including klusrmgr (1.3.1-1.oc00.i686).  When klusrmgr.exe executes as part of the rpm install, it crashes with the following error:

    Line 6 of _GroupExistGroup in klusrmgr.VRM:
    +++                       Do i = 1 To Groupname.0;
    *** Error 41 Bad arithmetic conversion
    Line 8 of _GroupAddNew in klusrmgr.VRM:
    +++                   If \ _GroupExistGroup(NewGrp);
    Line 4 of _GroupAddDefaults in klusrmgr.VRM:
    +++                 ok = _GroupAddNew('bin', 1, 'root,bin,daemon,');
    Line 14 of _InitResetMasterPasswdGroups in klusrmgr.VRM:
    +++               Call _GroupAddDefaults;
    Line 15 of Main_Create in klusrmgr.VRM:
    +++         Call _InitResetMasterPasswdGroups;
    Line 50 of Main in klusrmgr.VRM:
    +++       Call Main_Create;
    Line 50 of Main in klusrmgr.VRM:
    +++     Interpret _VREEvent;

This error implies that `Groupname.0` is uninitialized at runtime.

**To Reproduce**
1. Perform an 'update existing installation' of ArcaOS 5.0.0 using a ArcaOS 5.0.5 beta DVD.
2. At the end of phase 1, do not reboot automatically but open the management console.
3. Open a command prompt and edit STARTUP.CMD on the installed system. Locate the line which runs install.exe and insert the parameter "/t" before the "/Logs" parameter.
4. Reboot and allow the update to continue.  The error occurs during the "updating RPM packages" (group 1) section. A VX-REXX error popup appears, blocking the install from continuing until dismissed.  The file "lcu;.err" in the \sys\install directory contains the error trace.

**Expected behavior**
The installation should proceed without errors.

**Desktop (please complete the following information):**
 - OS: ArcaOS 5.0.5 (beta) installing on top of ArcaOS 5.0.0.

**Comment by altsan** [comment]
An easier reproduction scenario:
On an ArcaOS 5.0.0 system, simply run 'yum update libc'.

The same error occurs during klusrmgr update.  

It should be noted that ArcaOS 5.0.0 did not include klusrmgr, so this installs it for the first time.

**Comment by herwigb** [comment]
This is issue 3 in https://github.com/bitwiseworks/klusrmgr/issues/3

**Comment by herwigb** [comment]
[klusrmgr-132-testfix.zip](https://github.com/bitwiseworks/rpm-issues/files/4466011/klusrmgr-132-testfix.zip)

**Comment by altsan** [comment]
Hi Herwig,

This build appears to have fixed it, thanks.  Will you guys be building an updated RPM with this soon?  (If not, we can build a provisional one, but I'm sure you'd prefer to get that out yourselves.)

BTW, the link you posted above (to bitwiseworks/klusrmgr) only produces an HTTP 404 error.

Thanks!

**Comment by LewisR** [comment]
Hi, Herwig...

Per https://mantis.arcanoae.com/view.php?id=2830#c18230, the update to klusrmgr-1.3.2-2 now produces the following non-dismissable error during postin scriptlet processing:

Line 6 of _GroupExistGID in klusrmgr.VRM:
+++ Do i = 1 To GGid.0;

Oh, and to echo what Alex has said, it seems that the klusrmgr repository is not accessible to the rest of us.

Cheers

**Comment by SilvanScherrer** [comment]
Try latest klusrmgr. It should fix it.

**Comment by LewisR** [comment]
Confirmed here that 1.3.2-3 updates silently.
