### ISSUE TITLE
Please move highmem 1.0.2-1 to release

### ISSUE THREAD

**Issue by LewisR** [bitwiseworks/rpm-issues#8]
It seems that this new build addresses some serious shortcomings WRT handling large modules, and seems to work as designed. I recommend getting it moved to release ASAP.

**Comment by LewisR** [comment]
Ignore this. I see that Steve and I were requesting the same thing, and I was unaware that there was a separate project for highmem.

**Comment by dmik** [comment]
This is a more appropriate place, reopening.

**Comment by dmik** [comment]
Done, await for it to be reindexed.
