### ISSUE TITLE
usermod does not quite operate as documented and does not support whitespace lines.

### ISSUE THREAD

**Issue by StevenLevine** [bitwiseworks/rpm-issues#9]
usermod -l appears to always rewrite all files it references.  This is not what one would expect from the -l option.

usermod does not ignore/preserve lines consisting of only white space according to the typical standards.  Whitespace lines in master.password are treated as errors or sometimes rewritten as ::::::.  Whitespace lines group are rewritten as :*::.

**Comment by herwigb** [comment]
fixed in klusrmgr 1.4.4
